version: '3.4'
services:
  viteb_docker:
    image: node:alpine
    container_name: viteb_docker
    entrypoint: /bin/sh
    ports:
      - '4000:4000'
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true